### PR TITLE
Feat: Add make_index() for easy index creation

### PR DESCRIPTION
**Pull request by ctjlewis**
Easily build an index for a given dictionary of weights and lookback period.

## Example
```python
FAANG = qs.utils.make_index(
    {
        'FB': 0.2,
        'AAPL': 0.2,
        'AMZN': 0.2,
        'NFLX': 0.2,
        'GOOG': 0.2
    },
)

qs.plots.snapshot(FAANG.dropna(), "SPY")
```

**Output:**
image

### CODE REVIEW

**Comment by ctjlewis** [comment]
Hate to ping you @ranaroussi, was wondering if you had seen this PR - it should be super easy to review, please lmk if I can do anything to help further.

**Comment by pchaganti** [comment]
👍

**Comment by ctjlewis** [comment]
Hate to ping you @ranaroussi, wondering if you would mind reviewing? Also, if you need maintainers, this is a great project and I'd be happy to help out.

**Comment by ranaroussi** [comment]
H @ctjlewis - I'm merging this and will be including it in the next release this week.

I'd love to see a rebalance option for method - could be nice :)

```python
FAANG = qs.utils.make_index(
    {
        'FB': 0.2,
        'AAPL': 0.2,
        'AMZN': 0.2,
        'NFLX': 0.2,
        'GOOG': 0.2
    }, 
    rebalance="1M"
)
```

**Comment by ctjlewis** [comment]
Thanks so much @ranaroussi, super sorry for pinging. I will definitely work on that next! Good note.

**Pull request merged**
